// Svelte/Tabs.svelte
<script>
  import TabButton from "./TabButton.svelte";
  import TabArea from "./TabArea.svelte";

  export let tabs = []
  var selected = 0;

  function tabClick(id) {
    selected = id;
  }
</script>

<style>
  * {
    font-family: sans-serif;
  }
</style>

<div class="tabs">
    {#each tabs as tab, i}
        <TabButton
            id={i}
            name={tab.name}
            selected={selected === i}
            on:selection={e => tabClick(e.detail)}
        />
    {/each}

    <TabArea content={tabs[selected].content} />
</div>

// React/src/components/Tabs.js
import { TabButton } from "./TabButton";
import { TabArea } from "./TabArea";
import { useState } from "react";

import "../styles.css";

export const Tabs = (props) => {
  // Precisa do setSelected para fazer a separação de get/set
  const [selected, setSelected] = useState(0);

  return (
    <div className="tabs">
      {props.tabs.map((tab, i) => (
        <TabButton
          name={tab.name}
          selected={i === selected}
          onClick={() => setSelected(i)}
          key={i}
        />
      ))}

      <TabArea content={props.tabs[selected].content} />
    </div>
  );
};
